cd data/
wget https://physionet.org/physiobank/database/ltafdb/00.atr
wget https://physionet.org/physiobank/database/ltafdb/00.dat
wget https://physionet.org/physiobank/database/ltafdb/00.hea
wget https://physionet.org/physiobank/database/ltafdb/00.qrs
wget https://physionet.org/physiobank/database/ltafdb/01.atr
wget https://physionet.org/physiobank/database/ltafdb/01.dat
wget https://physionet.org/physiobank/database/ltafdb/01.hea
wget https://physionet.org/physiobank/database/ltafdb/01.qrs
wget https://physionet.org/physiobank/database/ltafdb/03.atr
wget https://physionet.org/physiobank/database/ltafdb/03.dat
wget https://physionet.org/physiobank/database/ltafdb/03.hea
wget https://physionet.org/physiobank/database/ltafdb/03.qrs
wget https://physionet.org/physiobank/database/ltafdb/05.atr
wget https://physionet.org/physiobank/database/ltafdb/05.dat
wget https://physionet.org/physiobank/database/ltafdb/05.hea
wget https://physionet.org/physiobank/database/ltafdb/05.qrs
wget https://physionet.org/physiobank/database/ltafdb/06.atr
wget https://physionet.org/physiobank/database/ltafdb/06.dat
wget https://physionet.org/physiobank/database/ltafdb/06.hea
wget https://physionet.org/physiobank/database/ltafdb/06.qrs
wget https://physionet.org/physiobank/database/ltafdb/07.atr
wget https://physionet.org/physiobank/database/ltafdb/07.dat
wget https://physionet.org/physiobank/database/ltafdb/07.hea
wget https://physionet.org/physiobank/database/ltafdb/07.qrs
wget https://physionet.org/physiobank/database/ltafdb/08.atr
wget https://physionet.org/physiobank/database/ltafdb/08.dat
wget https://physionet.org/physiobank/database/ltafdb/08.hea
wget https://physionet.org/physiobank/database/ltafdb/08.qrs
wget https://physionet.org/physiobank/database/ltafdb/10.atr
wget https://physionet.org/physiobank/database/ltafdb/10.dat
wget https://physionet.org/physiobank/database/ltafdb/10.hea
wget https://physionet.org/physiobank/database/ltafdb/10.qrs
wget https://physionet.org/physiobank/database/ltafdb/100.atr
wget https://physionet.org/physiobank/database/ltafdb/100.dat
wget https://physionet.org/physiobank/database/ltafdb/100.hea
wget https://physionet.org/physiobank/database/ltafdb/100.qrs
wget https://physionet.org/physiobank/database/ltafdb/101.atr
wget https://physionet.org/physiobank/database/ltafdb/101.dat
wget https://physionet.org/physiobank/database/ltafdb/101.hea
wget https://physionet.org/physiobank/database/ltafdb/101.qrs
wget https://physionet.org/physiobank/database/ltafdb/102.atr
wget https://physionet.org/physiobank/database/ltafdb/102.dat
wget https://physionet.org/physiobank/database/ltafdb/102.hea
wget https://physionet.org/physiobank/database/ltafdb/102.qrs
wget https://physionet.org/physiobank/database/ltafdb/103.atr
wget https://physionet.org/physiobank/database/ltafdb/103.dat
wget https://physionet.org/physiobank/database/ltafdb/103.hea
wget https://physionet.org/physiobank/database/ltafdb/103.qrs
wget https://physionet.org/physiobank/database/ltafdb/104.atr
wget https://physionet.org/physiobank/database/ltafdb/104.dat
wget https://physionet.org/physiobank/database/ltafdb/104.hea
wget https://physionet.org/physiobank/database/ltafdb/104.qrs
wget https://physionet.org/physiobank/database/ltafdb/105.atr
wget https://physionet.org/physiobank/database/ltafdb/105.dat
wget https://physionet.org/physiobank/database/ltafdb/105.hea
wget https://physionet.org/physiobank/database/ltafdb/105.qrs
wget https://physionet.org/physiobank/database/ltafdb/11.atr
wget https://physionet.org/physiobank/database/ltafdb/11.dat
wget https://physionet.org/physiobank/database/ltafdb/11.hea
wget https://physionet.org/physiobank/database/ltafdb/11.qrs
wget https://physionet.org/physiobank/database/ltafdb/110.atr
wget https://physionet.org/physiobank/database/ltafdb/110.dat
wget https://physionet.org/physiobank/database/ltafdb/110.hea
wget https://physionet.org/physiobank/database/ltafdb/110.qrs
wget https://physionet.org/physiobank/database/ltafdb/111.atr
wget https://physionet.org/physiobank/database/ltafdb/111.dat
wget https://physionet.org/physiobank/database/ltafdb/111.hea
wget https://physionet.org/physiobank/database/ltafdb/111.qrs
wget https://physionet.org/physiobank/database/ltafdb/112.atr
wget https://physionet.org/physiobank/database/ltafdb/112.dat
wget https://physionet.org/physiobank/database/ltafdb/112.hea
wget https://physionet.org/physiobank/database/ltafdb/112.qrs
wget https://physionet.org/physiobank/database/ltafdb/113.atr
wget https://physionet.org/physiobank/database/ltafdb/113.dat
wget https://physionet.org/physiobank/database/ltafdb/113.hea
wget https://physionet.org/physiobank/database/ltafdb/113.qrs
wget https://physionet.org/physiobank/database/ltafdb/114.atr
wget https://physionet.org/physiobank/database/ltafdb/114.dat
wget https://physionet.org/physiobank/database/ltafdb/114.hea
wget https://physionet.org/physiobank/database/ltafdb/114.qrs
wget https://physionet.org/physiobank/database/ltafdb/115.atr
wget https://physionet.org/physiobank/database/ltafdb/115.dat
wget https://physionet.org/physiobank/database/ltafdb/115.hea
wget https://physionet.org/physiobank/database/ltafdb/115.qrs
wget https://physionet.org/physiobank/database/ltafdb/116.atr
wget https://physionet.org/physiobank/database/ltafdb/116.dat
wget https://physionet.org/physiobank/database/ltafdb/116.hea
wget https://physionet.org/physiobank/database/ltafdb/116.qrs
wget https://physionet.org/physiobank/database/ltafdb/117.atr
wget https://physionet.org/physiobank/database/ltafdb/117.dat
wget https://physionet.org/physiobank/database/ltafdb/117.hea
wget https://physionet.org/physiobank/database/ltafdb/117.qrs
wget https://physionet.org/physiobank/database/ltafdb/118.atr
wget https://physionet.org/physiobank/database/ltafdb/118.dat
wget https://physionet.org/physiobank/database/ltafdb/118.hea
wget https://physionet.org/physiobank/database/ltafdb/118.qrs
wget https://physionet.org/physiobank/database/ltafdb/119.atr
wget https://physionet.org/physiobank/database/ltafdb/119.dat
wget https://physionet.org/physiobank/database/ltafdb/119.hea
wget https://physionet.org/physiobank/database/ltafdb/119.qrs
wget https://physionet.org/physiobank/database/ltafdb/12.atr
wget https://physionet.org/physiobank/database/ltafdb/12.dat
wget https://physionet.org/physiobank/database/ltafdb/12.hea
wget https://physionet.org/physiobank/database/ltafdb/12.qrs
wget https://physionet.org/physiobank/database/ltafdb/120.atr
wget https://physionet.org/physiobank/database/ltafdb/120.dat
wget https://physionet.org/physiobank/database/ltafdb/120.hea
wget https://physionet.org/physiobank/database/ltafdb/120.qrs
wget https://physionet.org/physiobank/database/ltafdb/121.atr
wget https://physionet.org/physiobank/database/ltafdb/121.dat
wget https://physionet.org/physiobank/database/ltafdb/121.hea
wget https://physionet.org/physiobank/database/ltafdb/121.qrs
wget https://physionet.org/physiobank/database/ltafdb/122.atr
wget https://physionet.org/physiobank/database/ltafdb/122.dat
wget https://physionet.org/physiobank/database/ltafdb/122.hea
wget https://physionet.org/physiobank/database/ltafdb/122.qrs
wget https://physionet.org/physiobank/database/ltafdb/13.atr
wget https://physionet.org/physiobank/database/ltafdb/13.dat
wget https://physionet.org/physiobank/database/ltafdb/13.hea
wget https://physionet.org/physiobank/database/ltafdb/13.qrs
wget https://physionet.org/physiobank/database/ltafdb/15.atr
wget https://physionet.org/physiobank/database/ltafdb/15.dat
wget https://physionet.org/physiobank/database/ltafdb/15.hea
wget https://physionet.org/physiobank/database/ltafdb/15.qrs
wget https://physionet.org/physiobank/database/ltafdb/16.atr
wget https://physionet.org/physiobank/database/ltafdb/16.dat
wget https://physionet.org/physiobank/database/ltafdb/16.hea
wget https://physionet.org/physiobank/database/ltafdb/16.qrs
wget https://physionet.org/physiobank/database/ltafdb/17.atr
wget https://physionet.org/physiobank/database/ltafdb/17.dat
wget https://physionet.org/physiobank/database/ltafdb/17.hea
wget https://physionet.org/physiobank/database/ltafdb/17.qrs
wget https://physionet.org/physiobank/database/ltafdb/18.atr
wget https://physionet.org/physiobank/database/ltafdb/18.dat
wget https://physionet.org/physiobank/database/ltafdb/18.hea
wget https://physionet.org/physiobank/database/ltafdb/18.qrs
wget https://physionet.org/physiobank/database/ltafdb/19.atr
wget https://physionet.org/physiobank/database/ltafdb/19.dat
wget https://physionet.org/physiobank/database/ltafdb/19.hea
wget https://physionet.org/physiobank/database/ltafdb/19.qrs
wget https://physionet.org/physiobank/database/ltafdb/20.atr
wget https://physionet.org/physiobank/database/ltafdb/20.dat
wget https://physionet.org/physiobank/database/ltafdb/20.hea
wget https://physionet.org/physiobank/database/ltafdb/20.qrs
wget https://physionet.org/physiobank/database/ltafdb/200.atr
wget https://physionet.org/physiobank/database/ltafdb/200.dat
wget https://physionet.org/physiobank/database/ltafdb/200.hea
wget https://physionet.org/physiobank/database/ltafdb/200.qrs
wget https://physionet.org/physiobank/database/ltafdb/201.atr
wget https://physionet.org/physiobank/database/ltafdb/201.dat
wget https://physionet.org/physiobank/database/ltafdb/201.hea
wget https://physionet.org/physiobank/database/ltafdb/201.qrs
wget https://physionet.org/physiobank/database/ltafdb/202.atr
wget https://physionet.org/physiobank/database/ltafdb/202.dat
wget https://physionet.org/physiobank/database/ltafdb/202.hea
wget https://physionet.org/physiobank/database/ltafdb/202.qrs
wget https://physionet.org/physiobank/database/ltafdb/203.atr
wget https://physionet.org/physiobank/database/ltafdb/203.dat
wget https://physionet.org/physiobank/database/ltafdb/203.hea
wget https://physionet.org/physiobank/database/ltafdb/203.qrs
wget https://physionet.org/physiobank/database/ltafdb/204.atr
wget https://physionet.org/physiobank/database/ltafdb/204.dat
wget https://physionet.org/physiobank/database/ltafdb/204.hea
wget https://physionet.org/physiobank/database/ltafdb/204.qrs
wget https://physionet.org/physiobank/database/ltafdb/205.atr
wget https://physionet.org/physiobank/database/ltafdb/205.dat
wget https://physionet.org/physiobank/database/ltafdb/205.hea
wget https://physionet.org/physiobank/database/ltafdb/205.qrs
wget https://physionet.org/physiobank/database/ltafdb/206.atr
wget https://physionet.org/physiobank/database/ltafdb/206.dat
wget https://physionet.org/physiobank/database/ltafdb/206.hea
wget https://physionet.org/physiobank/database/ltafdb/206.qrs
wget https://physionet.org/physiobank/database/ltafdb/207.atr
wget https://physionet.org/physiobank/database/ltafdb/207.dat
wget https://physionet.org/physiobank/database/ltafdb/207.hea
wget https://physionet.org/physiobank/database/ltafdb/207.qrs
wget https://physionet.org/physiobank/database/ltafdb/208.atr
wget https://physionet.org/physiobank/database/ltafdb/208.dat
wget https://physionet.org/physiobank/database/ltafdb/208.hea
wget https://physionet.org/physiobank/database/ltafdb/208.qrs
wget https://physionet.org/physiobank/database/ltafdb/21.atr
wget https://physionet.org/physiobank/database/ltafdb/21.dat
wget https://physionet.org/physiobank/database/ltafdb/21.hea
wget https://physionet.org/physiobank/database/ltafdb/21.qrs
wget https://physionet.org/physiobank/database/ltafdb/22.atr
wget https://physionet.org/physiobank/database/ltafdb/22.dat
wget https://physionet.org/physiobank/database/ltafdb/22.hea
wget https://physionet.org/physiobank/database/ltafdb/22.qrs
wget https://physionet.org/physiobank/database/ltafdb/23.atr
wget https://physionet.org/physiobank/database/ltafdb/23.dat
wget https://physionet.org/physiobank/database/ltafdb/23.hea
wget https://physionet.org/physiobank/database/ltafdb/23.qrs
wget https://physionet.org/physiobank/database/ltafdb/24.atr
wget https://physionet.org/physiobank/database/ltafdb/24.dat
wget https://physionet.org/physiobank/database/ltafdb/24.hea
wget https://physionet.org/physiobank/database/ltafdb/24.qrs
wget https://physionet.org/physiobank/database/ltafdb/25.atr
wget https://physionet.org/physiobank/database/ltafdb/25.dat
wget https://physionet.org/physiobank/database/ltafdb/25.hea
wget https://physionet.org/physiobank/database/ltafdb/25.qrs
wget https://physionet.org/physiobank/database/ltafdb/26.atr
wget https://physionet.org/physiobank/database/ltafdb/26.dat
wget https://physionet.org/physiobank/database/ltafdb/26.hea
wget https://physionet.org/physiobank/database/ltafdb/26.qrs
wget https://physionet.org/physiobank/database/ltafdb/28.atr
wget https://physionet.org/physiobank/database/ltafdb/28.dat
wget https://physionet.org/physiobank/database/ltafdb/28.hea
wget https://physionet.org/physiobank/database/ltafdb/28.qrs
wget https://physionet.org/physiobank/database/ltafdb/30.atr
wget https://physionet.org/physiobank/database/ltafdb/30.dat
wget https://physionet.org/physiobank/database/ltafdb/30.hea
wget https://physionet.org/physiobank/database/ltafdb/30.qrs
wget https://physionet.org/physiobank/database/ltafdb/32.atr
wget https://physionet.org/physiobank/database/ltafdb/32.dat
wget https://physionet.org/physiobank/database/ltafdb/32.hea
wget https://physionet.org/physiobank/database/ltafdb/32.qrs
wget https://physionet.org/physiobank/database/ltafdb/33.atr
wget https://physionet.org/physiobank/database/ltafdb/33.dat
wget https://physionet.org/physiobank/database/ltafdb/33.hea
wget https://physionet.org/physiobank/database/ltafdb/33.qrs
wget https://physionet.org/physiobank/database/ltafdb/34.atr
wget https://physionet.org/physiobank/database/ltafdb/34.dat
wget https://physionet.org/physiobank/database/ltafdb/34.hea
wget https://physionet.org/physiobank/database/ltafdb/34.qrs
wget https://physionet.org/physiobank/database/ltafdb/35.atr
wget https://physionet.org/physiobank/database/ltafdb/35.dat
wget https://physionet.org/physiobank/database/ltafdb/35.hea
wget https://physionet.org/physiobank/database/ltafdb/35.qrs
wget https://physionet.org/physiobank/database/ltafdb/37.atr
wget https://physionet.org/physiobank/database/ltafdb/37.dat
wget https://physionet.org/physiobank/database/ltafdb/37.hea
wget https://physionet.org/physiobank/database/ltafdb/37.qrs
wget https://physionet.org/physiobank/database/ltafdb/38.atr
wget https://physionet.org/physiobank/database/ltafdb/38.dat
wget https://physionet.org/physiobank/database/ltafdb/38.hea
wget https://physionet.org/physiobank/database/ltafdb/38.qrs
wget https://physionet.org/physiobank/database/ltafdb/39.atr
wget https://physionet.org/physiobank/database/ltafdb/39.dat
wget https://physionet.org/physiobank/database/ltafdb/39.hea
wget https://physionet.org/physiobank/database/ltafdb/39.qrs
wget https://physionet.org/physiobank/database/ltafdb/42.atr
wget https://physionet.org/physiobank/database/ltafdb/42.dat
wget https://physionet.org/physiobank/database/ltafdb/42.hea
wget https://physionet.org/physiobank/database/ltafdb/42.qrs
wget https://physionet.org/physiobank/database/ltafdb/43.atr
wget https://physionet.org/physiobank/database/ltafdb/43.dat
wget https://physionet.org/physiobank/database/ltafdb/43.hea
wget https://physionet.org/physiobank/database/ltafdb/43.qrs
wget https://physionet.org/physiobank/database/ltafdb/44.atr
wget https://physionet.org/physiobank/database/ltafdb/44.dat
wget https://physionet.org/physiobank/database/ltafdb/44.hea
wget https://physionet.org/physiobank/database/ltafdb/44.qrs
wget https://physionet.org/physiobank/database/ltafdb/45.atr
wget https://physionet.org/physiobank/database/ltafdb/45.dat
wget https://physionet.org/physiobank/database/ltafdb/45.hea
wget https://physionet.org/physiobank/database/ltafdb/45.qrs
wget https://physionet.org/physiobank/database/ltafdb/47.atr
wget https://physionet.org/physiobank/database/ltafdb/47.dat
wget https://physionet.org/physiobank/database/ltafdb/47.hea
wget https://physionet.org/physiobank/database/ltafdb/47.qrs
wget https://physionet.org/physiobank/database/ltafdb/48.atr
wget https://physionet.org/physiobank/database/ltafdb/48.dat
wget https://physionet.org/physiobank/database/ltafdb/48.hea
wget https://physionet.org/physiobank/database/ltafdb/48.qrs
wget https://physionet.org/physiobank/database/ltafdb/49.atr
wget https://physionet.org/physiobank/database/ltafdb/49.dat
wget https://physionet.org/physiobank/database/ltafdb/49.hea
wget https://physionet.org/physiobank/database/ltafdb/49.qrs
wget https://physionet.org/physiobank/database/ltafdb/51.atr
wget https://physionet.org/physiobank/database/ltafdb/51.dat
wget https://physionet.org/physiobank/database/ltafdb/51.hea
wget https://physionet.org/physiobank/database/ltafdb/51.qrs
wget https://physionet.org/physiobank/database/ltafdb/53.atr
wget https://physionet.org/physiobank/database/ltafdb/53.dat
wget https://physionet.org/physiobank/database/ltafdb/53.hea
wget https://physionet.org/physiobank/database/ltafdb/53.qrs
wget https://physionet.org/physiobank/database/ltafdb/54.atr
wget https://physionet.org/physiobank/database/ltafdb/54.dat
wget https://physionet.org/physiobank/database/ltafdb/54.hea
wget https://physionet.org/physiobank/database/ltafdb/54.qrs
wget https://physionet.org/physiobank/database/ltafdb/55.atr
wget https://physionet.org/physiobank/database/ltafdb/55.dat
wget https://physionet.org/physiobank/database/ltafdb/55.hea
wget https://physionet.org/physiobank/database/ltafdb/55.qrs
wget https://physionet.org/physiobank/database/ltafdb/56.atr
wget https://physionet.org/physiobank/database/ltafdb/56.dat
wget https://physionet.org/physiobank/database/ltafdb/56.hea
wget https://physionet.org/physiobank/database/ltafdb/56.qrs
wget https://physionet.org/physiobank/database/ltafdb/58.atr
wget https://physionet.org/physiobank/database/ltafdb/58.dat
wget https://physionet.org/physiobank/database/ltafdb/58.hea
wget https://physionet.org/physiobank/database/ltafdb/58.qrs
wget https://physionet.org/physiobank/database/ltafdb/60.atr
wget https://physionet.org/physiobank/database/ltafdb/60.dat
wget https://physionet.org/physiobank/database/ltafdb/60.hea
wget https://physionet.org/physiobank/database/ltafdb/60.qrs
wget https://physionet.org/physiobank/database/ltafdb/62.atr
wget https://physionet.org/physiobank/database/ltafdb/62.dat
wget https://physionet.org/physiobank/database/ltafdb/62.hea
wget https://physionet.org/physiobank/database/ltafdb/62.qrs
wget https://physionet.org/physiobank/database/ltafdb/64.atr
wget https://physionet.org/physiobank/database/ltafdb/64.dat
wget https://physionet.org/physiobank/database/ltafdb/64.hea
wget https://physionet.org/physiobank/database/ltafdb/64.qrs
wget https://physionet.org/physiobank/database/ltafdb/65.atr
wget https://physionet.org/physiobank/database/ltafdb/65.dat
wget https://physionet.org/physiobank/database/ltafdb/65.hea
wget https://physionet.org/physiobank/database/ltafdb/65.qrs
wget https://physionet.org/physiobank/database/ltafdb/68.atr
wget https://physionet.org/physiobank/database/ltafdb/68.dat
wget https://physionet.org/physiobank/database/ltafdb/68.hea
wget https://physionet.org/physiobank/database/ltafdb/68.qrs
wget https://physionet.org/physiobank/database/ltafdb/69.atr
wget https://physionet.org/physiobank/database/ltafdb/69.dat
wget https://physionet.org/physiobank/database/ltafdb/69.hea
wget https://physionet.org/physiobank/database/ltafdb/69.qrs
wget https://physionet.org/physiobank/database/ltafdb/70.atr
wget https://physionet.org/physiobank/database/ltafdb/70.dat
wget https://physionet.org/physiobank/database/ltafdb/70.hea
wget https://physionet.org/physiobank/database/ltafdb/70.qrs
wget https://physionet.org/physiobank/database/ltafdb/71.atr
wget https://physionet.org/physiobank/database/ltafdb/71.dat
wget https://physionet.org/physiobank/database/ltafdb/71.hea
wget https://physionet.org/physiobank/database/ltafdb/71.qrs
wget https://physionet.org/physiobank/database/ltafdb/72.atr
wget https://physionet.org/physiobank/database/ltafdb/72.dat
wget https://physionet.org/physiobank/database/ltafdb/72.hea
wget https://physionet.org/physiobank/database/ltafdb/72.qrs
wget https://physionet.org/physiobank/database/ltafdb/74.atr
wget https://physionet.org/physiobank/database/ltafdb/74.dat
wget https://physionet.org/physiobank/database/ltafdb/74.hea
wget https://physionet.org/physiobank/database/ltafdb/74.qrs
wget https://physionet.org/physiobank/database/ltafdb/75.atr
wget https://physionet.org/physiobank/database/ltafdb/75.dat
wget https://physionet.org/physiobank/database/ltafdb/75.hea
wget https://physionet.org/physiobank/database/ltafdb/75.qrs
